language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t ghostyat/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ghostyat/react-test npm test

after_success:
  - docker build -t ghostyat/multi-client ./client
  - docker build -t ghostyat/multi-nginx ./nginx
  - docker build -t ghostyat/multi-worker ./worker
  - docker build -t ghostyat/multi-server ./server
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push to docker hub
  - docker push ghostyat/multi-client
  - docker push ghostyat/multi-nginx
  - docker push ghostyat/multi-worker
  - docker push ghostyat/multi-server

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-186416302941"
  bucket_path: "docker-multi"
  on:
    branch: master   
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

#